cargo-features = ["edition"]

[package]
name = "microforth"
version = "0.1.0"
authors = ["Hannes Karppila <hannes.karppila@gmail.com>"]

edition = "2018"

[dependencies]
rustyline = "1.0"
dirs = "1.0"